-- Safra agricultural activity header.
CREATE TABLE llx_safra_activity (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    entity INTEGER NOT NULL DEFAULT 1,
    ref VARCHAR(128) NOT NULL,
    label VARCHAR(255) NOT NULL,
    type VARCHAR(32) NOT NULL DEFAULT 'outro',
    status INTEGER NOT NULL DEFAULT 0,
    priority INTEGER NOT NULL DEFAULT 1,
    progress DOUBLE(6,2) DEFAULT 0,
    season VARCHAR(32),
    crop_name VARCHAR(128),
    cultivar_name VARCHAR(128),
    fk_project INTEGER,
    fk_task INTEGER,
    fk_thirdparty INTEGER,
    fk_fieldplot INTEGER,
    area_planned DOUBLE(24,8) DEFAULT 0,
    area_done DOUBLE(24,8) DEFAULT 0,
    area_total DOUBLE(24,8) DEFAULT 0,
    date_planned_start DATETIME,
    date_planned_end DATETIME,
    date_start DATETIME,
    date_end DATETIME,
    weather VARCHAR(255),
    note_public TEXT,
    note_private TEXT,
    date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    fk_user_creat INTEGER NOT NULL,
    fk_user_modif INTEGER,
    UNIQUE INDEX uk_safra_activity_ref (entity, ref),
    INDEX idx_safra_activity_entity (entity),
    INDEX idx_safra_activity_status (status),
    INDEX idx_safra_activity_type (type),
    INDEX idx_safra_activity_priority (priority),
    INDEX idx_safra_activity_season (season),
    INDEX idx_safra_activity_crop (crop_name),
    INDEX idx_safra_activity_fk_project (fk_project),
    INDEX idx_safra_activity_fk_task (fk_task),
    INDEX idx_safra_activity_fk_thirdparty (fk_thirdparty),
    INDEX idx_safra_activity_fk_fieldplot (fk_fieldplot),
    INDEX idx_safra_activity_date_planned_start (date_planned_start),
    CONSTRAINT llx_safra_activity_fk_project FOREIGN KEY (fk_project) REFERENCES llx_projet(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_fk_task FOREIGN KEY (fk_task) REFERENCES llx_projet_task(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_fk_thirdparty FOREIGN KEY (fk_thirdparty) REFERENCES llx_societe(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_fk_fieldplot FOREIGN KEY (fk_fieldplot) REFERENCES llx_safra_talhao(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_fk_user_creat FOREIGN KEY (fk_user_creat) REFERENCES llx_user(rowid),
    CONSTRAINT llx_safra_activity_fk_user_modif FOREIGN KEY (fk_user_modif) REFERENCES llx_user(rowid) ON DELETE SET NULL
) ENGINE=innodb;
