-- Safra agricultural activity input lines.
CREATE TABLE llx_safra_activity_line (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    entity INTEGER NOT NULL DEFAULT 1,
    fk_activity INTEGER NOT NULL,
    position INTEGER DEFAULT 0,
    fk_product INTEGER,
    fk_warehouse INTEGER,
    movement_type VARCHAR(16) NOT NULL DEFAULT 'consume',
    area_planned DOUBLE(24,8) DEFAULT 0,
    area_done DOUBLE(24,8) DEFAULT 0,
    dose_planned DOUBLE(24,8) DEFAULT 0,
    dose_done DOUBLE(24,8) DEFAULT 0,
    dose_unit VARCHAR(32),
    qty_planned DOUBLE(24,8) DEFAULT 0,
    qty_done DOUBLE(24,8) DEFAULT 0,
    total DOUBLE(24,8) DEFAULT 0,
    area_applied DOUBLE(24,8) DEFAULT 0,
    dose DOUBLE(24,8) DEFAULT 0,
    unit_cost DOUBLE(24,8) DEFAULT 0,
    note TEXT,
    date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    fk_user_creat INTEGER,
    fk_user_modif INTEGER,
    INDEX idx_safra_activity_line_entity (entity),
    INDEX idx_safra_activity_line_fk_activity (fk_activity),
    INDEX idx_safra_activity_line_fk_product (fk_product),
    INDEX idx_safra_activity_line_fk_warehouse (fk_warehouse),
    INDEX idx_safra_activity_line_movement_type (movement_type),
    CONSTRAINT llx_safra_activity_line_fk_activity FOREIGN KEY (fk_activity) REFERENCES llx_safra_activity(rowid) ON DELETE CASCADE,
    CONSTRAINT llx_safra_activity_line_fk_product FOREIGN KEY (fk_product) REFERENCES llx_product(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_line_fk_warehouse FOREIGN KEY (fk_warehouse) REFERENCES llx_entrepot(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_line_fk_user_creat FOREIGN KEY (fk_user_creat) REFERENCES llx_user(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_line_fk_user_modif FOREIGN KEY (fk_user_modif) REFERENCES llx_user(rowid) ON DELETE SET NULL
) ENGINE=innodb;
