-- Safra activity lines for inputs/products.
CREATE TABLE llx_safra_activity_line (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    entity INTEGER NOT NULL DEFAULT 1,
    fk_activity INTEGER NOT NULL,
    fk_product INTEGER,
    area_applied DOUBLE DEFAULT 0,
    dose DOUBLE DEFAULT 0,
    dose_unit VARCHAR(32),
    total DOUBLE DEFAULT 0,
    movement_type VARCHAR(16) DEFAULT 'consume',
    fk_warehouse INTEGER,
    date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    fk_user_creat INTEGER,
    fk_user_modif INTEGER,
    INDEX idx_safra_activity_line_entity (entity),
    INDEX idx_safra_activity_line_fk_activity (fk_activity),
    INDEX idx_safra_activity_line_fk_product (fk_product),
    INDEX idx_safra_activity_line_fk_warehouse (fk_warehouse),
    CONSTRAINT llx_safra_activity_line_fk_activity FOREIGN KEY (fk_activity) REFERENCES llx_safra_activity(rowid) ON DELETE CASCADE,
    CONSTRAINT llx_safra_activity_line_fk_product FOREIGN KEY (fk_product) REFERENCES llx_product(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_line_fk_warehouse FOREIGN KEY (fk_warehouse) REFERENCES llx_entrepot(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_line_fk_user_creat FOREIGN KEY (fk_user_creat) REFERENCES llx_user(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_line_fk_user_modif FOREIGN KEY (fk_user_modif) REFERENCES llx_user(rowid) ON DELETE SET NULL
) ENGINE=innodb;
