-- Safra activity header table.
CREATE TABLE llx_safra_activity (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    entity INTEGER NOT NULL DEFAULT 1,
    ref VARCHAR(128) NOT NULL,
    label VARCHAR(255) NOT NULL,
    fk_project INTEGER,
    fk_task INTEGER,
    fk_thirdparty INTEGER,
    fk_fieldplot INTEGER,
    area_total DOUBLE DEFAULT 0,
    type VARCHAR(32) NOT NULL,
    status INTEGER NOT NULL DEFAULT 0,
    note_public TEXT,
    note_private TEXT,
    date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    fk_user_creat INTEGER NOT NULL,
    fk_user_modif INTEGER,
    UNIQUE INDEX uk_safra_activity_ref (entity, ref),
    INDEX idx_safra_activity_entity (entity),
    INDEX idx_safra_activity_fk_project (fk_project),
    INDEX idx_safra_activity_fk_task (fk_task),
    INDEX idx_safra_activity_fk_thirdparty (fk_thirdparty),
    INDEX idx_safra_activity_fk_fieldplot (fk_fieldplot),
    INDEX idx_safra_activity_status (status),
    INDEX idx_safra_activity_type (type),
    CONSTRAINT llx_safra_activity_fk_project FOREIGN KEY (fk_project) REFERENCES llx_projet(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_fk_task FOREIGN KEY (fk_task) REFERENCES llx_projet_task(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_fk_thirdparty FOREIGN KEY (fk_thirdparty) REFERENCES llx_societe(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_fk_fieldplot FOREIGN KEY (fk_fieldplot) REFERENCES llx_safra_talhao(rowid) ON DELETE SET NULL,
    CONSTRAINT llx_safra_activity_fk_user_creat FOREIGN KEY (fk_user_creat) REFERENCES llx_user(rowid),
    CONSTRAINT llx_safra_activity_fk_user_modif FOREIGN KEY (fk_user_modif) REFERENCES llx_user(rowid) ON DELETE SET NULL
) ENGINE=innodb;
